version: '3'
services:
  nginx:
    depends_on:
    - ws
    container_name: nginx
    build: nginx/.
    image: mpr/nginx
    ports:
    - "80:80"
    - "443:443"
    stdin_open: true
    tty: true
    volumes:
      - /var/www/static/mpr:/var/www/static/mpr
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    domainname: meuportaretrato.com
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  ws:
    container_name: ws
    build: .
    ports:
      - "8181:8181"
    restart: always
    image: mpr/ws
    environment:
      profile: prd
    stdin_open: true
    tty: true
    volumes:
    - /etc/localtime:/etc/localtime
    - /var/www/static/mpr:/var/www/static/mpr
    domainname: api.meuportaretrato.com
