version: '2'
services:
  jobs-hml:
    ports:
      - "8181:8181"
    image: mpr/ws
    environment:
      profile: dev
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    domainname: meuportaretrato.com.br