version: '2'
services:
  be:
    depends_on:
      - db
    build: .
    ports:
      - "8181:8181"
    image: mpr/ws
    environment:
      profile: dev
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    - /var/www/static/mpr:/var/www/static/mpr
    domainname: meuportaretrato.com.br
  db:
    build: mysql/.
    image: mpr/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=753951
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    stdin_open: true
    tty: true
    domainname: meuportaretrato.com  