version: '2'
services:
  nginx:
    depends_on:
    - ws
    container_name: nginx
    build: nginx/.
    image: mpr/nginx
    ports:
    - "80:80"
    stdin_open: true
    tty: true
    volumes:
    - /var/www/static/mpr:/var/www/static/mpr
    domainname: meuportaretrato.com
  ws:
    container_name: ws
    build: .
    ports:
      - "8181:8181"
    restart: always
    image: mpr/ws
    environment:
      profile: prd
    stdin_open: true
    tty: true
    volumes:
    - /etc/localtime:/etc/localtime
    - /var/www/static/mpr:/var/www/static/mpr
    domainname: api.meuportaretrato.com
