version: '2'
services:
  be:
    ports:
      - "8181:8181"
    image: mpr/ws
    environment:
      profile: dev
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    domainname: meuportaretrato.com.br