server:
  port: 8181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 20
      test-on-borrow: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

  profiles:
    active: "dev"

#lembre-se se trocar esse path, precisa trocar o volume no docker-compose e o mkdir no Dockerfile
mpr:
  pathImg: /var/www/static/mpr/images
  folderPreview: p
  folderDestaque: d
  staticHost: static.meuportaretrato.com

---

spring:
  profiles: "dev"
  datasource:
    url: jdbc:mysql://mysql.meuportaretrato.com:3306/mpr?autoReconnect=true&useSSL=false
    username: root
    password: 753951

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG

---

spring:
  profiles: "prd"
  datasource:
    url: jdbc:mysql://mysql:3306/mpr?autoReconnect=true&useSSL=false
    username: root
    password: 753951
logging:
  level:
    org:
      springframework: ERROR
      hibernate: ERROR
    br:
      com:
        braspress: DEBUG