server:
  port: 8181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 20
      maximumPoolSize: 100
      maxLifetime: 120000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  profiles:
    active: "prd"

#lembre-se se trocar esse path, precisa trocar o volume no docker-compose e o mkdir no Dockerfile
mpr:
  pathImg: /var/www/static/mpr/images
  folderPreview: p
  folderDestaque: d
  folderCatalogo: catalogo
  folderCliente: cliente
  staticHost: http://stc.meuportaretrato.com
  baseUrlDestaque: ${mpr.staticHost}/images/${mpr.folderDestaque}/
  baseUrlPreview: ${mpr.staticHost}/images/${mpr.folderPreview}/
  imgSemFoto: ${mpr.staticHost}/images/semFoto.png

---

spring:
  profiles: "dev"
  datasource:
    url: jdbc:mysql://192.168.1.32:3306/mpr?autoReconnect=true&useSSL=false
    username: root
    password: 753951

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG

---

spring:
  profiles: "prd"
  datasource:
    url: jdbc:mysql://mysql.meuportaretrato.com:3306/mpr?autoReconnect=true&useSSL=false
    username: mpr
    password: "*753951*"
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG


---

spring:
  profiles: "tests"

mpr:
  pathImg: /tmp
  folderPreview: p
  folderDestaque: d
  folderCatalogo: catalogo
  folderCliente: cliente
  staticHost: http://stc.meuportaretrato.com
  baseUrlDestaque: ${mpr.staticHost}/images/${mpr.folderDestaque}/
  baseUrlPreview: ${mpr.staticHost}/images/${mpr.folderPreview}/
  imgSemFoto: ${mpr.staticHost}/images/semFoto.png
