server:
  port: 8181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 20 #default 20
      maximumPoolSize: 40 #30 por causa do limite free da amazon producao = 100
      leakDetectionThreshold: 20000
      #maxLifetime: 60000 #1min
      #connectionTimeout: 20000 #20s
      #idleTimeout: 30000 #30s

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  profiles:
    active: "dev"

#lembre-se de trocar esse path, precisa trocar o volume no docker-compose e o mkdir no Dockerfile
mpr:
  pathImg: /var/www/static/mpr/images
  folderPreview: p
  folderDestaque: d
  folderCatalogo: catalogo
  folderCliente: cliente
  staticHost: http://stc.meuportaretrato.com
  baseUrlDestaque: ${mpr.staticHost}/images/${mpr.folderDestaque}/
  baseUrlPreview: ${mpr.staticHost}/images/${mpr.folderPreview}/
  baseUrlCliente: ${mpr.staticHost}/images/${mpr.folderCliente}/
  baseUrlCatalogo: ${mpr.staticHost}/images/${mpr.folderCatalogo}/
  imgSemFoto: ${mpr.staticHost}/images/semFoto.png

---

spring:
  profiles: "dev"
  datasource:
    url: jdbc:mysql://mysql.meuportaretrato.com:3306/mpr?useSSL=false
    username: mpr
    password: "*753951*"

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG
    com:
      zaxxer:
        hikari: DEBUG

cielo:
  merchantId: 224e8290-1485-4a9b-a1b0-8f05745b724d
  merchantKey: SRQHPVROYXHQEWODLTJXOFAZPODLVNVOKEKAARZV

---

spring:
  profiles: "prd"
  datasource:
    url: jdbc:mysql://mysql.meuportaretrato.com:3306/mpr?autoReconnect=true&useSSL=false
    username: mpr
    password: "*753951*"
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG

cielo:
  merchantId: 224e8290-1485-4a9b-a1b0-8f05745b724d
  merchantKey: SRQHPVROYXHQEWODLTJXOFAZPODLVNVOKEKAARZV


---

spring:
  profiles: "tests"

mpr:
  pathImg: /tmp
  folderPreview: p
  folderDestaque: d
  folderCatalogo: catalogo
  folderCliente: cliente
  staticHost: http://stc.meuportaretrato.com
  baseUrlDestaque: ${mpr.staticHost}/images/${mpr.folderDestaque}/
  baseUrlPreview: ${mpr.staticHost}/images/${mpr.folderPreview}/
  baseUrlCliente: ${mpr.staticHost}/images/${mpr.folderCliente}/
  baseUrlCatalogo: ${mpr.staticHost}/images/${mpr.folderCatalogo}/
  imgSemFoto: ${mpr.staticHost}/images/semFoto.png

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: INFO
    br:
      com:
        mpr: DEBUG

cielo:
  merchantId: 224e8290-1485-4a9b-a1b0-8f05745b724d
  merchantKey: SRQHPVROYXHQEWODLTJXOFAZPODLVNVOKEKAARZV