DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS APP_CONFIG_SITE;


CREATE TABLE IF NOT EXISTS CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (60) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CELULAR VARCHAR(13) NOT NULL,
    ANIVERSARIO DATE
);



CREATE TABLE IF NOT EXISTS APP_CONFIG_SITE(
    ID INT NOT NULL AUTO_INCREMENT,
    CHAVE VARCHAR(100) NOT NULL,
    VALOR VARCHAR(100),
    DATA_ATUALIZACAO DATE,
    DATA_CRIACAO  DATE
);
