DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS CUPOM_DESCONTO;


CREATE TABLE IF NOT EXISTS CLIENTE(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (60) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CELULAR VARCHAR(13) NOT NULL,
    ANIVERSARIO DATE
);

CREATE TABLE IF NOT EXISTS CUPOM_DESCONTO(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL,
    HASH VARCHAR(8) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    PROMOCAO NUMERIC(1) NOT NULL,
    PORCENTAGEM DECIMAL(10,2) NOT NULL,
    QTDE_UTILIZADA INT
    
);

CREATE TABLE IF NOT EXISTS ENDERECO(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(80) NOT NULL,
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(60) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    UF VARCHAR(2) NOT NULL
);
