FROM nginx:1.15-alpine

MAINTAINER Wagner Jeronimo A. Araujo

ADD apimpr.conf /etc/nginx/conf.d/apimpr.conf
ADD stcmpr.conf /etc/nginx/conf.d/stcmpr.conf
ADD default.conf /etc/nginx/conf.d/default.conf